### PR TITLE
chore: get tests running in standalone configuration

### PR DESCRIPTION
**Pull request by bdunderscore**

### CODE REVIEW

**Comment by bdunderscore** [comment]
TODO: Can we use nuget to obtain these dependencies? Is this the right long-term mechanism?

**Comment by bdunderscore** [comment]
Tests currently pass in editor, but don't quite work in CI yet:
* auto (2019) finds zero tests
* 2022.3.5f1 doesn't install the NUnit dependency

**Comment by bdunderscore** [comment]
@kaikoga

**Comment by kaikoga** [comment]
Hmm... artifacts from 2022 standalone test looks correct, and my local 2019 standalone project (with quickly-wrapped-up kaikoga/ndmf-deps) is able to handle symlinked unit tests, so something is missing in 2019 standalone setup...

```
Error: Could not load signature of System.Collections.Immutable.ImmutableArray:Create due to: Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none> 
(Filename: ./Runtime/Mono/MonoAttributeHelpers.cpp Line: 363)

Unloading broken assembly Packages/nadena.dev.ndmf/Dependencies/System.Collections.Immutable.dll, this assembly can cause crashes in the runtime 
(Filename: ./Runtime/Mono/MonoManager.cpp Line: 1233)
```

Adding System.Memory.dll, which is referenced through System.Collections.Immutable.dll, may fix this issue in Unity 2019.

These DLLs comes with .NET Standard 2.1, default of Unity 2021, but not with .NET 4.x, which is default of Unity 2019.

(Now we have more problems... :confused: )

**Pull request merged**
