### PR TITLE
Adding a proposal for an avatar build framework.

### PR DESCRIPTION
**Pull request by bdunderscore**
This RFC proposes a common framework for build-time transformations to improve cross-plugin compatibility.
I'd appreciate feedback on the approach, and I'd like to get a feel as to whether folks are interested in adopting it.

Rendered: https://github.com/bdunderscore/avatar-build-plugin-framework/blob/rfc-0001/rfc/0001-framework.md

### CODE REVIEW

**Comment by anatawa12** [comment]
Thank you for creating RFC.

It looks good for most points but I think AnimationAdjuster lacks some features.

Because AvatarOptimizer merges multiple skinned meshes, I want some API to express & process merging components and renaming some properties in AnimationAdjuster.

In addition, because AvatarOptimizer merges multiple components into one, I think it's better to replace reference to source components to merged component so I want to extend AnimationAdjuster to not only for animations but also for components.

Also, I want AnimationAdjuster (extended for components) to have feature to track blendshape index, which is not used by animations.
I use the index mapping to fix eyelidsBlendshapes in VRCAvatarDescriptor in AvatarOptimizer.
For reference, In ObjectMapping in AvatarOptimizer, I'm using pseudo animation properties

**Comment by bdunderscore** [comment]
Moving source components is more difficult as components can't be detached from their owning GameObject and moved around. I could see adding a `RemapComponent(Type componentType, GameObject from, GameObject to)` however.

As for blendshapes, I feel like that's getting out of scope for a general purpose component. But there could be helpers for applying transformations or visitors to all animations though. `context.Get<AnimationAdjuster>().TransformClips(clip => newClip)` or `.VisitClips(clip => readOnlyAction(clip))` sort of thing?

I do want to be careful not to add too much at once. It's easier to add more features in the future than it is to remove ones that turned out problematic.

**Comment by anatawa12** [comment]
> I could see adding a RemapComponent(Type componentType, GameObject from, GameObject to) however.

It's like what I'm considering. Sorry for not being clear enough.

> But there could be helpers for applying transformations or visitors to all animations though. context.Get<AnimationAdjuster>().TransformClips(clip => newClip) or .VisitClips(clip => readOnlyAction(clip)) sort of thing?

I think it will not work well.
I think when either `TransformClips` or `VisitClips` is called, AnimationAdjuster have to save path of GameObjects at the time and pass animation with saved paths and it's not efficient.

> I do want to be careful not to add too much at once. It's easier to add more features in the future than it is to remove ones that turned out problematic.

I agree so I withdraw requesting feature for blendshape indexes and references for now.

**Comment by bdunderscore** [comment]
It might be valuable to virtualize the animation clips (ie - transform them into an internal representation once, and transform back into real clips later). This has a number of advantages, in particular Modular Avatar had to resort to SerializedProperty manipulations of animation clips in some places due to Unity API limitations. However, because it increases the API scope significantly I feel that it's probably best to leave it out of the minimal viable product.

**Comment by bdunderscore** [comment]
Thinking about this some more: I think it would be better to expose a concept of plugins vs phases. Specifically, we expose to the end-user the idea of a plugin (e.g., Modular Avatar, Avatar Optimizer, VRCFury, etc), which internally consists of one or more passes. By default, all passes of a plugin are executed together in sequence, but you can choose to add explicit pass-level constraints to interleave your plugin in the middle of another.

I'm thinking of an API a bit like this, for example:

```csharp
[assembly:DefinePlugin(typeof(ModularMarshmallow))]

class ModularMarshmallow : AvatarBuildPlugin {
    public override string QualifiedName => "foo.bar.modular-marshmallow";

    public void configure() {
        // Top-level runsAfter/runsBefore are applied to the first/last pass defined by the plugin
        runsAfter(Sequence.BeginGenerate); // Actually a no-op plugin provided by the framework
        withPass("generate-objects", ModularMarshmallow.GenerateObjects);
        // An ordering constraint is automatically generated between passes defined by the same plugin
        withPass("move-objects", ModularMarshmallow.MoveObjectsAround).AfterPass(ModularAvatarPasses.BeforeFixupAnimations);
        withPass("cleanup", ModularMarshmallow.Cleanup).AfterPlugin("nadena.dev.modular-avatar");
    }

    static void GenerateObjects(BuildContext context) { ... }
    static void MoveObjectsAround(BuildContext context) { ... }
}

```

Meanwhile in ModularAvatar:

```csharp

public static class ModularAvatarPasses {
  const string BeforeFixupAnimations = "nadena.dev.modular-avatar.before-fixup-animations";
}

// ...
static class ModularAvatarPlugin : AvatarBuildPlugin {
    public override string QualifiedName => "nadena.dev.modular-avatar";

    public void configure() {
        // ...
        withPass("visible-head-accessory", VisibleHeadAccessory.Process);
        withPass("before-fixup-animations", (context) => {}).expose(); // make available for dependency declarations
        withPass("mesh-settings", MeshSettings.Process);
        // ...
    }
}
```

At the UI level, users would be shown just the high-level plugin name, and can reorder those. This ordering is used as a tiebreaker; our toposort algorithm looks a bit like this:

```
convert all 'runs before' constraints to 'runs after' constraints

while (unexecuted passes remain):
  obtain the list of passes where all constraints are satisfied
  if list is empty: error out (unsatisfiable constraints)
  sort list by the order in which plugins started execution; for unexecuted plugins, order them by the user-selected order
  execute the first plugin
```

So in our case above we have:

```
* BeginGenerate (no-op)
* ModularMarshmallow: generate-objects
* ...
* [ other MA passes ]
* MA: visible-head-accessory
* MA: before-fixup-animations (no-op)
* ModularMarshmallow: move-objects
* MA: mesh-settings
* [ other MA passes ]
* ModularMarshmallow: cleanup
* [ ... ]
```

**Comment by kaikoga** [comment]
To express my support to the concept of (build-time) avatar transformations, I would like to add following clause to the Future possibilities section (or at least write some proposal-like material somewhere by myself):

```
- Non-VRChat Avatar support: Removing depedencies to VRCSDK would open possibilities to avatar transformations for avatar formats outside VRChat. While this could appeal to more potential users, an extra layer should be created in the framework to abstract the dependencies to VRCSDK and introduce more complexity, and perhaps increase user support cost.
```

Of course we can go the "abstracted VRCSDK dependency way" from the beginning, but I think the initial delivery speed with only VRCSDK support is higher priority, therefore future possibilities. (We can just try to avoid exposing potentially breaking APIs for now.)

**Comment by anatawa12** [comment]
The plugin system looks good but there is one small thing should be changed I think.

On the ModularMarshmallow side, to run some pass between `"nadena.dev.modular-avatar.visible-head-accessory"` phase and `"nadena.dev.modular-avatar.mesh-settings"` phase, it calls `.AfterPass(ModularAvatarPasses.BeforeFixupAnimations)`.

However, I think it's not clear enough because it looks can be after `"nadena.dev.modular-avatar.mesh-settings"` phase so I think it should be something like `.InPass(ModularAvatarPasses.BeforeFixupAnimations);`.

**Comment by bdunderscore** [comment]
Hmm. Regarding the pass ordering dependencies, the idea is each plugin internally consists of passes, and the order between passes can be controlled by the pass/plugin author. Having a pass run inside another pass doesn't really make very much sense, in my opinion.

I am considering the idea of having "phases" - built-in phases are general categories you can put your passes into to try to get a general level of consistency. For example, MA will use this to resolve serialized paths to concrete objects before any hierarchy manipulation occurs, while allowing the rest of its processing to run later. Perhaps having user-defined phases might make sense, but internally these are just no-op passes which are used as a "runs-after" dependency target.

**Comment by bdunderscore** [comment]
I also have been making some changes as I prototype the implementation - expect the next iteration of this to be a call for comments on the implemented API, with some examples of ported assets.

**Pull request closed without merging**
