### PR TITLE
fix: incorrect display for zh-* culture names in lang switcher

### PR DESCRIPTION
**Pull request by bdunderscore**
Closes: #171

### CODE REVIEW

**Comment by Misaka-L** [comment]
still incorrect....

**Comment by Misaka-L** [comment]
| Language Code | Display Name |
|--------|--------|
| zh-Hans | 简体中文 |
| zh-Hant | 繁體中文 |

**Comment by bdunderscore** [comment]
Hm. The challenge with this is I don't speak languages other than Japanese and English, and can't confirm the accuracy of these language names - that's why I tried to pull it from the system culture info database.

Doing anything better probably requires localization of the language names in the culture itself; the challenge here is choosing which NDMF plugin to pull that language name from. There's probably a dataset somewhere with a full list of these codes and their native names; once I find one with a suitable license I'll address this that way. Until then, at least this way you can tell which one it is? Maybe?

**Comment by Misaka-L** [comment]
> Hm. The challenge with this is I don't speak languages other than Japanese and English, and can't confirm the accuracy of these language names - that's why I tried to pull it from the system culture info database.
> 
> Doing anything better probably requires localization of the language names in the culture itself; the challenge here is choosing which NDMF plugin to pull that language name from. There's probably a dataset somewhere with a full list of these codes and their native names; once I find one with a suitable license I'll address this that way. Until then, at least this way you can tell which one it is? Maybe?

image

reply from vrchat staff. Their soulation is make some special cases for language which native name is incorrect

**Comment by bdunderscore** [comment]
I think I found a usable datasource in ICU. Does this look about right?

```
    "zh": "中文",
    "zh_Hans": "中文（简体）",
    "zh_Hans_CN": "中文（简体，中国）",
    "zh_Hans_HK": "中文（简体，中国香港特别行政区）",
    "zh_Hans_MO": "中文（简体，中国澳门特别行政区）",
    "zh_Hans_SG": "中文（简体，新加坡）",
    "zh_Hant": "中文（繁體）",
    "zh_Hant_HK": "中文（繁體字，中國香港特別行政區）",
    "zh_Hant_MO": "中文（繁體字，中國澳門特別行政區）",
    "zh_Hant_TW": "中文（繁體，台灣）",
```

**Comment by Misaka-L** [comment]
> I think I found a usable datasource in ICU. Does this look about right?
> 
> ```
>     "zh": "中文",
>     "zh_Hans": "中文（简体）",
>     "zh_Hans_CN": "中文（简体，中国）",
>     "zh_Hans_HK": "中文（简体，中国香港特别行政区）",
>     "zh_Hans_MO": "中文（简体，中国澳门特别行政区）",
>     "zh_Hans_SG": "中文（简体，新加坡）",
>     "zh_Hant": "中文（繁體）",
>     "zh_Hant_HK": "中文（繁體字，中國香港特別行政區）",
>     "zh_Hant_MO": "中文（繁體字，中國澳門特別行政區）",
>     "zh_Hant_TW": "中文（繁體，台灣）",
> ```

I think it's correct.....

**Comment by Misaka-L** [comment]
by the way, the implementation of .net CultureInfo didn't meet the IETF's BCP 47....

see https://www.w3.org/International/questions/qa-choosing-language-tags.en.html

**Comment by bdunderscore** [comment]
Yeah, the language selection logic in NDMF probably isn't perfect either. I don't have good test cases for this at the moment though, nor do I have consistent translators for MA for languages other than en-US or ja-JP, so it's not a high priority to sort that out at the moment...

**Comment by Misaka-L** [comment]
> Yeah, the language selection logic in NDMF probably isn't perfect either. I don't have good test cases for this at the moment though, nor do I have consistent translators for MA for languages other than en-US or ja-JP, so it's not a high priority to sort that out at the moment...

i think the current solution is enought. thanks!

**Comment by bdunderscore** [comment]
image

**Pull request merged**
